"""Tests for the OCR pipeline in :mod:`penge.vault.ocr`.

The ``embedded text fast path`` is exercised against the synthetic
fixtures generated by ``tools/generate_vault_fixtures.py``. The
``Tesseract OCR fallback`` test is gated on the ``tesseract`` system
binary so the suite still passes on machines without OCR system deps.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from unittest import mock

import pytest

from penge.vault.errors import OCRError
from penge.vault.ocr import OCRConfig, extract_text

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.mark.parametrize(
    ("filename", "needle"),
    [
        ("sample_dk.pdf", "Aarsoversigt"),
        ("sample_de.pdf", "Jahressteuerbescheinigung"),
        ("sample_en.pdf", "Annual Statement"),
    ],
)
def test_extract_text_uses_embedded_fast_path(filename: str, needle: str) -> None:
    """Reportlab-generated fixtures embed selectable text — no OCR needed."""

    result = extract_text(FIXTURES / filename)
    assert result.extracted_via == "embedded"
    assert needle in result.text
    assert result.pages == 1


def test_extract_text_rejects_non_pdf(tmp_path: Path) -> None:
    p = tmp_path / "x.txt"
    p.write_text("not a pdf")
    with pytest.raises(OCRError):
        extract_text(p)


def test_extract_text_rejects_missing_file(tmp_path: Path) -> None:
    with pytest.raises(OCRError):
        extract_text(tmp_path / "nope.pdf")


def test_extract_text_falls_back_to_ocr_when_embedded_empty(tmp_path: Path) -> None:
    """If pdfplumber returns empty pages we hit the OCR path with the configured langs."""

    pdf = tmp_path / "scanned.pdf"
    pdf.write_bytes(b"%PDF-1.4\n%fake\n")  # contents irrelevant — pdfplumber is mocked

    fake_pdfplumber = mock.MagicMock()
    fake_pdf_ctx = mock.MagicMock()
    fake_page = mock.MagicMock()
    fake_page.extract_text.return_value = ""
    fake_pdf_ctx.__enter__.return_value.pages = [fake_page]
    fake_pdf_ctx.__exit__.return_value = False
    fake_pdfplumber.open.return_value = fake_pdf_ctx

    fake_pdf2image = mock.MagicMock()
    fake_pdf2image.convert_from_path.return_value = [mock.MagicMock(name="page0")]

    fake_pytesseract = mock.MagicMock()
    fake_pytesseract.image_to_string.return_value = "Hello DK DE EN"

    with mock.patch.dict(
        "sys.modules",
        {
            "pdfplumber": fake_pdfplumber,
            "pdf2image": fake_pdf2image,
            "pytesseract": fake_pytesseract,
        },
    ):
        result = extract_text(pdf, OCRConfig(langs="dan+deu+eng", dpi=200))

    assert result.extracted_via == "ocr"
    assert "Hello DK DE EN" in result.text
    fake_pytesseract.image_to_string.assert_called_once()
    _, kwargs = fake_pytesseract.image_to_string.call_args
    assert kwargs["lang"] == "dan+deu+eng"


@pytest.mark.skipif(shutil.which("tesseract") is None, reason="tesseract binary not installed")
def test_extract_text_uses_real_tesseract_when_available() -> None:
    """End-to-end: rasterise our embedded-text fixture and OCR it.

    We force the OCR path by patching pdfplumber to return empty so
    the embedded-text fast path does not short-circuit.
    """

    pytest.importorskip("pdf2image")
    pytest.importorskip("pytesseract")

    fake_pdfplumber = mock.MagicMock()
    fake_ctx = mock.MagicMock()
    fake_page = mock.MagicMock()
    fake_page.extract_text.return_value = ""
    fake_ctx.__enter__.return_value.pages = [fake_page]
    fake_ctx.__exit__.return_value = False
    fake_pdfplumber.open.return_value = fake_ctx

    with mock.patch.dict("sys.modules", {"pdfplumber": fake_pdfplumber}):
        result = extract_text(FIXTURES / "sample_en.pdf", OCRConfig(langs="eng", dpi=200))

    assert result.extracted_via == "ocr"
    # OCR is approximate; we look for a word with strong, unambiguous glyphs.
    assert "Statement" in result.text or "Annual" in result.text
