"""Generate the synthetic PFA Pensionsoversigt PDFs used by tests.

Run with::

    uv run --group parsers --group ocr python tools/generate_pfa_fixture.py

The ``parsers`` group provides ``reportlab`` (text PDF) and the
``ocr`` group provides ``pdf2image`` + ``Pillow`` which are used
to rasterise the text PDF into the image-only fixture. The script
overwrites two PDFs under ``tests/ingest/pfa/fixtures/``:

- ``sample_pensionsoversigt.pdf`` — text-embedded, exercises the
  pdfplumber fast path;
- ``sample_pensionsoversigt_scanned.pdf`` — image-only (no embedded
  text), exercises the OCR fallback path. Generated by rasterising
  the text PDF at low DPI so the host needs Tesseract DA+DEU to
  parse it.

Both fixtures use fictional policy numbers and amounts.
"""

from __future__ import annotations

import io
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

OUTPUT_DIR = Path(__file__).resolve().parents[1] / "tests" / "ingest" / "pfa" / "fixtures"
TEXT_PDF = OUTPUT_DIR / "sample_pensionsoversigt.pdf"
SCANNED_PDF = OUTPUT_DIR / "sample_pensionsoversigt_scanned.pdf"

POLICY_NUMBER = "12-345-678"
AS_OF = "31.12.2025"
PERIOD = "01.01.2025 - 31.12.2025"


def _scheme_table(
    header: str,
    *,
    primo: str,
    employer: str,
    employee: str,
    afkast: str,
    omkostninger: str,
    pal_skat: str,
    ultimo: str,
) -> Table:
    rows = [
        [header, ""],
        ["Primo", primo],
        ["Indbetaling - Arbejdsgiver", employer],
        ["Indbetaling - Privat", employee],
        ["Afkast", afkast],
        ["Omkostninger", omkostninger],
        ["PAL-skat", pal_skat],
        ["Ultimo", ultimo],
    ]
    table = Table(rows, colWidths=[280, 140])
    table.setStyle(
        TableStyle(
            [
                ("FONT", (0, 0), (-1, -1), "Helvetica", 10),
                ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 11),
                ("ALIGN", (1, 0), (1, -1), "RIGHT"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.black),
            ]
        )
    )
    return table


def _holdings_table(rows: list[tuple[str, str, str, str]]) -> Table:
    data = [["Investeringsprofil", "Andel", "Andele", "Markedsværdi"]]
    data.extend(list(row) for row in rows)
    table = Table(data, colWidths=[220, 60, 80, 100])
    table.setStyle(
        TableStyle(
            [
                ("FONT", (0, 0), (-1, -1), "Helvetica", 9),
                ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 10),
                ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.black),
            ]
        )
    )
    return table


def _build_text_pdf(buffer: io.BytesIO | Path) -> None:
    doc = SimpleDocTemplate(
        str(buffer) if isinstance(buffer, Path) else buffer,
        pagesize=A4,
        title="PFA Pensionsoversigt",
        author="PFA Pension (synthetic)",
    )
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("H1", parent=styles["Title"], fontSize=18, leading=22)
    body = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, leading=14)

    story = [
        Paragraph("PFA Pensionsoversigt", h1),
        Spacer(1, 8),
        Paragraph(f"Policenr.: {POLICY_NUMBER}", body),
        Paragraph(f"Opgjort pr. {AS_OF}", body),
        Paragraph(f"Optjeningsperiode: {PERIOD}", body),
        Spacer(1, 16),
        _scheme_table(
            "Aldersopsparing",
            primo="50.000,00",
            employer="0,00",
            employee="8.500,00",
            afkast="2.500,00",
            omkostninger="120,00",
            pal_skat="382,50",
            ultimo="60.497,50",
        ),
        Spacer(1, 12),
        _holdings_table(
            [
                ("PFA Plus AA", "60,00 %", "120,5", "36.298,50"),
                ("PFA Globale Aktier", "30,00 %", "60,2", "18.149,25"),
                ("PFA Hedge Lav Risiko", "10,00 %", "20,1", "6.049,75"),
                ("I alt", "100,00 %", "", "60.497,50"),
            ]
        ),
        Spacer(1, 16),
        _scheme_table(
            "Ratepension",
            primo="850.000,00",
            employer="63.000,00",
            employee="0,00",
            afkast="42.500,00",
            omkostninger="2.100,00",
            pal_skat="6.502,50",
            ultimo="946.897,50",
        ),
        Spacer(1, 12),
        _holdings_table(
            [
                ("PFA Plus C", "50,00 %", "1.500,0", "473.448,75"),
                ("PFA Globale Aktier", "40,00 %", "1.200,0", "378.759,00"),
                ("PFA Globale Obligationer", "10,00 %", "300,0", "94.689,75"),
            ]
        ),
        Spacer(1, 16),
        _scheme_table(
            "Livsvarig livrente",
            primo="120.000,00",
            employer="12.000,00",
            employee="0,00",
            afkast="6.000,00",
            omkostninger="350,00",
            pal_skat="918,00",
            ultimo="136.732,00",
        ),
    ]
    doc.build(story)


def _build_scanned_pdf() -> None:
    """Rasterise the text PDF at low DPI to produce an image-only PDF."""

    # Local imports so the text PDF generator works on hosts without
    # poppler / pdf2image available (the OCR fixture is regenerated
    # less frequently and only when the host has poppler installed).
    import pdf2image
    from PIL import Image

    buf = io.BytesIO()
    _build_text_pdf(buf)
    buf.seek(0)
    images: list[Image.Image] = pdf2image.convert_from_bytes(buf.read(), dpi=110)
    if not images:
        raise RuntimeError("pdf2image returned no pages")
    first, *rest = images
    first.save(
        SCANNED_PDF,
        "PDF",
        save_all=bool(rest),
        append_images=rest,
        resolution=110,
    )


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    _build_text_pdf(TEXT_PDF)
    _build_scanned_pdf()


if __name__ == "__main__":  # pragma: no cover
    main()
