/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/accounts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Accounts
     * @description Account dimension with IBAN and name suffix masked server-side.
     */
    get: operations["accounts_accounts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/allocation/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Allocation Current
     * @description Latest-day allocation grouped by entity, currency, or account kind.
     */
    get: operations["allocation_current_allocation_current_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/benchmarks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Benchmarks
     * @description Instruments with ingested price history, usable as benchmarks.
     */
    get: operations["benchmarks_benchmarks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/benchmarks/daily": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Benchmarks Daily
     * @description Daily close series of one benchmark, in its native currency.
     *
     *     An unknown instrument id yields an empty series, not an error —
     *     the UI treats it the same as "no prices in window".
     */
    get: operations["benchmarks_daily_benchmarks_daily_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cashflow/daily": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cashflow Daily
     * @description Daily cashflow series per account (absent days mean zero).
     */
    get: operations["cashflow_daily_cashflow_daily_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/connections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Connections Route
     * @description List every bank connection with its status and last-sync debug info.
     */
    get: operations["list_connections_route_connections_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/connections/aspsps": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Aspsps
     * @description List the Enable Banking ASPSPs this deployment can connect to.
     */
    get: operations["list_aspsps_connections_aspsps_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/connections/authorize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Authorize Route
     * @description Exchange the redirect code for a stored session.
     */
    post: operations["authorize_route_connections_authorize_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/connections/link": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Link Route
     * @description Start a consent and return the bank's consent URL.
     */
    post: operations["link_route_connections_link_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/connections/{connection_id}/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sync Route
     * @description Pull transactions + balances for one connection into Postgres.
     */
    post: operations["sync_route_connections__connection_id__sync_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/imports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Imports
     * @description List import sessions, newest first.
     */
    get: operations["list_imports_imports_get"];
    put?: never;
    /**
     * Create Import
     * @description Upload one statement, parse it, and stage its rows for review.
     */
    post: operations["create_import_imports_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/imports/{session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Import
     * @description Return one session with one page of its staged rows.
     */
    get: operations["get_import_imports__session_id__get"];
    put?: never;
    post?: never;
    /**
     * Discard Import
     * @description Discard a staged (or expired) session and delete its stored file.
     */
    delete: operations["discard_import_imports__session_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/imports/{session_id}/commit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Commit Import
     * @description Write all included rows to the raw tables via the loaders.
     */
    post: operations["commit_import_imports__session_id__commit_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/imports/{session_id}/rows/{row_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Patch Import Row
     * @description Correct, exclude, or re-map one staged row before commit.
     */
    patch: operations["patch_import_row_imports__session_id__rows__row_id__patch"];
    trace?: never;
  };
  "/imports/{session_id}/suggestions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Suggest Import Mappings
     * @description Ask the MCP suggestion tool for mapping proposals (ADR-0038).
     *
     *     The API only proxies: the deterministic rules live in the MCP
     *     server, which is the sole sanctioned LLM/AI data path. Returns 503
     *     when no MCP command is configured or the server is unreachable,
     *     502 when the tool itself rejects the call.
     */
    post: operations["suggest_import_mappings_imports__session_id__suggestions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/meta/freshness": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Meta Freshness
     * @description Latest data date and row count per mart, for staleness banners.
     */
    get: operations["meta_freshness_meta_freshness_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/net-worth/daily": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Net Worth Daily
     * @description Daily net-worth series, per account or summed per day.
     */
    get: operations["net_worth_daily_net_worth_daily_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/returns/daily": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns Daily
     * @description Daily return factors per scope from ``mart_returns_daily``.
     */
    get: operations["returns_daily_returns_daily_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/returns/fees": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns Fees
     * @description Yearly fee totals per account, for the fee-drag view.
     */
    get: operations["returns_fees_returns_fees_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/returns/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns Summary
     * @description Chain-linked TWR and MWR per scope key over the window.
     *
     *     Computation runs server-side through ``penge.analytics.returns``
     *     so the UI and any other client see identical figures. A scope key
     *     whose series cannot be chain-linked faithfully reports an ``error``
     *     note instead of a number.
     */
    get: operations["returns_summary_returns_summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AccountSummary
     * @description Account dimension row with identifiers masked server-side.
     *
     *     ``iban_masked`` keeps only the last four characters
     *     (``penge.web.mask.mask_iban``); the raw IBAN never leaves the API.
     */
    AccountSummary: {
      /** Account Id */
      account_id: string;
      /** Currency */
      currency: string;
      /** Entity Id */
      entity_id: string;
      /** Entity Name */
      entity_name: string;
      /** Iban Masked */
      iban_masked: string;
      /** Kind */
      kind: string;
      /** Name */
      name: string;
      /** Provider */
      provider: string;
    };
    /**
     * AllocationDimension
     * @description Grouping dimension for the current-allocation endpoint.
     * @enum {string}
     */
    AllocationDimension: "entity" | "currency" | "kind";
    /**
     * AllocationResponse
     * @description Current allocation snapshot grouped by one dimension.
     */
    AllocationResponse: {
      /** As Of */
      as_of: string | null;
      by: components["schemas"]["AllocationDimension"];
      /** Slices */
      slices: components["schemas"]["AllocationSlice"][];
    };
    /**
     * AllocationSlice
     * @description One slice of the latest-day allocation, grouped by a dimension.
     *
     *     ``weight_eur`` is this slice's share of the EUR total (0..1);
     *     ``None`` when the EUR total is zero or missing.
     */
    AllocationSlice: {
      /** Balance Dkk */
      balance_dkk: string | null;
      /** Balance Eur */
      balance_eur: string | null;
      /** Label */
      label: string;
      /** Weight Eur */
      weight_eur: string | null;
    };
    /**
     * AspspListResponse
     * @description The set of providers the deployment can connect to.
     */
    AspspListResponse: {
      /** Providers */
      providers: components["schemas"]["AspspOut"][];
    };
    /**
     * AspspOut
     * @description One selectable Enable Banking ASPSP.
     */
    AspspOut: {
      /** Aspsp Country */
      aspsp_country: string;
      /** Aspsp Name */
      aspsp_name: string;
      /** Default Currency */
      default_currency: string;
      /** Provider */
      provider: string;
    };
    /**
     * AuthorizeRequest
     * @description Exchange the redirect ``code`` for a stored session.
     */
    AuthorizeRequest: {
      /**
       * Code
       * @description The ?code= value from the callback.
       */
      code: string;
      /**
       * State
       * @description The ?state= value; binds the code to its pending connection.
       */
      state?: string | null;
    };
    /**
     * BenchmarkInfo
     * @description One instrument with ingested price history, usable as benchmark.
     */
    BenchmarkInfo: {
      /** Currency */
      currency: string;
      /** First As Of */
      first_as_of: string | null;
      /** Instrument Id */
      instrument_id: string;
      /** Last As Of */
      last_as_of: string | null;
      /** Name */
      name: string;
      /** Points */
      points: number;
      /** Ticker */
      ticker: string | null;
    };
    /**
     * BenchmarkPoint
     * @description One daily close of a benchmark instrument (native currency).
     */
    BenchmarkPoint: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Close */
      close: string;
      /** Currency */
      currency: string;
    };
    /**
     * BenchmarkSeriesResponse
     * @description Paginated daily close series for one benchmark instrument.
     */
    BenchmarkSeriesResponse: {
      /** Instrument Id */
      instrument_id: string;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Points */
      points: components["schemas"]["BenchmarkPoint"][];
      /** Total */
      total: number;
    };
    /** Body_create_import_imports_post */
    Body_create_import_imports_post: {
      /** Account Name */
      account_name?: string | null;
      /** Entity Name */
      entity_name?: string | null;
      /** File */
      file: string;
      /** Source */
      source?: string | null;
    };
    /**
     * CashflowPoint
     * @description One account-day row of ``mart_cashflow_daily``.
     *
     *     Days without transactions produce no row; consumers treat absent
     *     days as zero (same contract as the MCP ``query_cashflow`` tool).
     */
    CashflowPoint: {
      /** Account Currency */
      account_currency: string;
      /** Account Id */
      account_id: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Entity Id */
      entity_id: string;
      /** Inflow Acct Ccy */
      inflow_acct_ccy: string;
      /** Inflow Dkk */
      inflow_dkk: string | null;
      /** Inflow Eur */
      inflow_eur: string | null;
      /** Net Acct Ccy */
      net_acct_ccy: string;
      /** Net Dkk */
      net_dkk: string | null;
      /** Net Eur */
      net_eur: string | null;
      /** Outflow Acct Ccy */
      outflow_acct_ccy: string;
      /** Outflow Dkk */
      outflow_dkk: string | null;
      /** Outflow Eur */
      outflow_eur: string | null;
    };
    /**
     * CashflowSeriesResponse
     * @description Paginated cashflow series at account granularity.
     */
    CashflowSeriesResponse: {
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Points */
      points: components["schemas"]["CashflowPoint"][];
      /** Total */
      total: number;
    };
    /**
     * CommitCountsOut
     * @description Rows written by a commit, in loader vocabulary.
     */
    CommitCountsOut: {
      /** Accounts */
      accounts: number;
      /** Entities */
      entities: number;
      /** Holding Snapshots */
      holding_snapshots: number;
      /** Instruments */
      instruments: number;
      /** Transactions */
      transactions: number;
    };
    /**
     * CommitRequest
     * @description Optional commit-time parameters (override upload-time values).
     */
    CommitRequest: {
      /** Account Name */
      account_name?: string | null;
      /** Entity Name */
      entity_name?: string | null;
    };
    /**
     * CommitResponse
     * @description Result of committing a session.
     */
    CommitResponse: {
      counts: components["schemas"]["CommitCountsOut"];
      session: components["schemas"]["ImportSessionOut"];
    };
    /**
     * ConnectionAccountOut
     * @description One authorised account on a connection (no raw uid leaks to logs).
     */
    ConnectionAccountOut: {
      /** Currency */
      currency: string | null;
      /** Iban Masked */
      iban_masked: string | null;
      /** Name */
      name: string | null;
      /** Product */
      product: string | null;
    };
    /**
     * ConnectionErrorOut
     * @description Sanitised debug payload for a failed link/authorize/sync.
     */
    ConnectionErrorOut: {
      /**
       * At
       * Format: date-time
       */
      at: string;
      /** Code */
      code: string | null;
      /** Message */
      message: string;
      /** Status Code */
      status_code: number | null;
      /** Step */
      step: string;
    };
    /**
     * ConnectionListResponse
     * @description All known connections.
     */
    ConnectionListResponse: {
      /** Connections */
      connections: components["schemas"]["ConnectionOut"][];
    };
    /**
     * ConnectionOut
     * @description A bank connection as exposed to the UI.
     */
    ConnectionOut: {
      /** Accounts */
      accounts: components["schemas"]["ConnectionAccountOut"][];
      /** Aspsp Country */
      aspsp_country: string;
      /** Aspsp Name */
      aspsp_name: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Entity Name */
      entity_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      last_error: components["schemas"]["ConnectionErrorOut"] | null;
      /** Last Sync At */
      last_sync_at: string | null;
      /** Last Sync Status */
      last_sync_status: string | null;
      /** Provider */
      provider: string;
      /** Status */
      status: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Valid Until */
      valid_until: string | null;
    };
    /**
     * CurrencyReturnSummary
     * @description TWR/MWR figures for one measurement currency.
     *
     *     ``error`` carries a data-quality note when the series could not be
     *     chain-linked faithfully; all figures are then ``None`` rather than
     *     a fabricated number.
     */
    CurrencyReturnSummary: {
      /** Annualized Return */
      annualized_return: number | null;
      /** Cumulative Return */
      cumulative_return: string | null;
      /** Error */
      error: string | null;
      /** Mwr Annualized */
      mwr_annualized: number | null;
    };
    /**
     * FeeYearRow
     * @description Fees recorded for one account in one calendar year.
     *
     *     Sums explicit ``fee``-kind transactions plus the ``fee`` column on
     *     trades, converted at the forward-filled ECB rate of the fee date.
     */
    FeeYearRow: {
      /** Account Id */
      account_id: string;
      /** Fees Dkk */
      fees_dkk: string | null;
      /** Fees Eur */
      fees_eur: string | null;
      /** Year */
      year: number;
    };
    /**
     * FeesResponse
     * @description Yearly fee totals per account over one request window.
     */
    FeesResponse: {
      /** Rows */
      rows: components["schemas"]["FeeYearRow"][];
      /**
       * Since
       * Format: date
       */
      since: string;
      /**
       * Until
       * Format: date
       */
      until: string;
    };
    /**
     * FreshnessResponse
     * @description Freshness metadata for every mart the API serves.
     */
    FreshnessResponse: {
      /** Marts */
      marts: components["schemas"]["MartFreshness"][];
    };
    /**
     * GroupBy
     * @description Aggregation level for the net-worth series.
     * @enum {string}
     */
    GroupBy: "account" | "total";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * ImportRowOut
     * @description One staged row of an import session.
     */
    ImportRowOut: {
      /** Accepted At */
      accepted_at: string | null;
      /** Edited */
      edited: boolean;
      /** Excluded */
      excluded: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Issues */
      issues: components["schemas"]["RowIssue"][];
      /** Kind */
      kind: string;
      /** Mappings */
      mappings: {
        [key: string]: string;
      };
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /** Row Index */
      row_index: number;
      /** Status */
      status: string;
      /** Suggested By */
      suggested_by: string | null;
    };
    /**
     * ImportSessionListResponse
     * @description One page of import sessions, newest first.
     */
    ImportSessionListResponse: {
      /** Sessions */
      sessions: components["schemas"]["ImportSessionOut"][];
      /** Total */
      total: number;
    };
    /**
     * ImportSessionOut
     * @description One import session without its rows.
     */
    ImportSessionOut: {
      /** Committed At */
      committed_at: string | null;
      /** Content Sha256 */
      content_sha256: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error */
      error: string | null;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Original Filename */
      original_filename: string;
      /** Params */
      params: {
        [key: string]: unknown;
      };
      row_counts: components["schemas"]["RowCounts"];
      /** Source */
      source: string;
      /** Status */
      status: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ImportSessionWithRows
     * @description One import session plus one page of its rows.
     */
    ImportSessionWithRows: {
      /** Committed At */
      committed_at: string | null;
      /** Content Sha256 */
      content_sha256: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error */
      error: string | null;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Original Filename */
      original_filename: string;
      /** Params */
      params: {
        [key: string]: unknown;
      };
      row_counts: components["schemas"]["RowCounts"];
      /** Rows */
      rows: components["schemas"]["ImportRowOut"][];
      /** Source */
      source: string;
      /** Status */
      status: string;
      /** Total Rows */
      total_rows: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * LinkRequest
     * @description Start a consent for one provider.
     */
    LinkRequest: {
      /**
       * Entity Name
       * @description Canonical person the synced accounts belong to.
       */
      entity_name: string;
      /**
       * Provider
       * @description Penge provider slug: gls | ebank | lunar.
       */
      provider: string;
    };
    /**
     * LinkResponse
     * @description Where to send the browser to obtain consent.
     */
    LinkResponse: {
      /**
       * Connection Id
       * Format: uuid
       */
      connection_id: string;
      /** Consent Url */
      consent_url: string;
      /** State */
      state: string;
      /**
       * Valid Until
       * Format: date-time
       */
      valid_until: string;
    };
    /**
     * MappingSuggestionOut
     * @description One AI mapping suggestion for one staged row (ADR-0038).
     */
    MappingSuggestionOut: {
      /** Confidence */
      confidence: number;
      /** Field */
      field: string;
      /** Kind */
      kind: string;
      /** Reason */
      reason: string;
      /**
       * Row Id
       * Format: uuid
       */
      row_id: string;
      /** Row Index */
      row_index: number;
      /** Value */
      value: string;
    };
    /**
     * MartFreshness
     * @description Latest data date and row count for one mart.
     */
    MartFreshness: {
      /** Latest As Of */
      latest_as_of: string | null;
      /** Mart */
      mart: string;
      /** Row Count */
      row_count: number;
    };
    /**
     * NetWorthPoint
     * @description One account-day row of ``mart_net_worth_daily``.
     */
    NetWorthPoint: {
      /** Account Currency */
      account_currency: string;
      /** Account Id */
      account_id: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Balance Acct Ccy */
      balance_acct_ccy: string;
      /** Balance Dkk */
      balance_dkk: string | null;
      /** Balance Eur */
      balance_eur: string | null;
      /** Entity Id */
      entity_id: string;
    };
    /**
     * NetWorthSeriesResponse
     * @description Paginated net-worth series at account granularity.
     */
    NetWorthSeriesResponse: {
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Points */
      points: components["schemas"]["NetWorthPoint"][];
      /** Total */
      total: number;
    };
    /**
     * NetWorthTotalPoint
     * @description One day of the net-worth series summed across all accounts.
     */
    NetWorthTotalPoint: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Balance Dkk */
      balance_dkk: string | null;
      /** Balance Eur */
      balance_eur: string | null;
    };
    /**
     * NetWorthTotalSeriesResponse
     * @description Net-worth series aggregated to one row per day.
     */
    NetWorthTotalSeriesResponse: {
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Points */
      points: components["schemas"]["NetWorthTotalPoint"][];
      /** Total */
      total: number;
    };
    /**
     * ReturnsPoint
     * @description One scope-day row of ``mart_returns_daily``.
     *
     *     The return factor follows the start-of-day flow convention
     *     ``end_mv / (begin_mv + net_flow)`` and is ``None`` on days without
     *     capital at risk (ADR-0039).
     */
    ReturnsPoint: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Begin Mv Dkk */
      begin_mv_dkk: string | null;
      /** Begin Mv Eur */
      begin_mv_eur: string | null;
      /** End Mv Dkk */
      end_mv_dkk: string | null;
      /** End Mv Eur */
      end_mv_eur: string | null;
      /** Net Flow Dkk */
      net_flow_dkk: string | null;
      /** Net Flow Eur */
      net_flow_eur: string | null;
      /** Return Factor Dkk */
      return_factor_dkk: string | null;
      /** Return Factor Eur */
      return_factor_eur: string | null;
      scope: components["schemas"]["ReturnsScope"];
      /** Scope Key */
      scope_key: string;
    };
    /**
     * ReturnsScope
     * @description Scope dimension of ``mart_returns_daily`` (ADR-0039).
     * @enum {string}
     */
    ReturnsScope: "account" | "asset_class" | "household";
    /**
     * ReturnsSeriesResponse
     * @description Paginated daily return-factor series for one scope.
     */
    ReturnsSeriesResponse: {
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Points */
      points: components["schemas"]["ReturnsPoint"][];
      /** Total */
      total: number;
    };
    /**
     * ReturnsSummaryEntry
     * @description Chain-linked TWR and MWR for one scope key over the window.
     */
    ReturnsSummaryEntry: {
      /** Days */
      days: number;
      dkk: components["schemas"]["CurrencyReturnSummary"];
      /** End Date */
      end_date: string | null;
      eur: components["schemas"]["CurrencyReturnSummary"];
      scope: components["schemas"]["ReturnsScope"];
      /** Scope Key */
      scope_key: string;
      /** Start Date */
      start_date: string | null;
    };
    /**
     * ReturnsSummaryResponse
     * @description Per-scope-key return summaries over one request window.
     */
    ReturnsSummaryResponse: {
      /** Entries */
      entries: components["schemas"]["ReturnsSummaryEntry"][];
      scope: components["schemas"]["ReturnsScope"];
      /**
       * Since
       * Format: date
       */
      since: string;
      /**
       * Until
       * Format: date
       */
      until: string;
    };
    /**
     * RowCounts
     * @description Aggregated review state of a session's rows.
     */
    RowCounts: {
      /** Error */
      error: number;
      /** Excluded */
      excluded: number;
      /** Ok */
      ok: number;
      /** Total */
      total: number;
      /** Warning */
      warning: number;
    };
    /**
     * RowIssue
     * @description One validation or duplicate finding on a staged row.
     */
    RowIssue: {
      /** Code */
      code: string;
      /** Detail */
      detail: string;
    };
    /**
     * RowPatchRequest
     * @description Corrections to one staged row before commit.
     */
    RowPatchRequest: {
      /** Excluded */
      excluded?: boolean | null;
      /** Mappings */
      mappings?: {
        [key: string]: string;
      } | null;
      /** Payload */
      payload?: {
        [key: string]: unknown;
      } | null;
      /** Suggested By */
      suggested_by?: string | null;
    };
    /**
     * SuggestionSessionOut
     * @description Session echo returned by the MCP suggestion tool.
     */
    SuggestionSessionOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Rows Considered */
      rows_considered: number;
      /** Source */
      source: string;
      /** Status */
      status: string;
    };
    /**
     * SuggestionsResponse
     * @description Mapping suggestions for one staged session, as returned by MCP.
     */
    SuggestionsResponse: {
      session: components["schemas"]["SuggestionSessionOut"];
      /** Suggested By */
      suggested_by: string;
      /** Suggestions */
      suggestions: components["schemas"]["MappingSuggestionOut"][];
    };
    /**
     * SyncResponse
     * @description Outcome of a sync run.
     */
    SyncResponse: {
      connection: components["schemas"]["ConnectionOut"];
      /** Holding Snapshots */
      holding_snapshots: number;
      /** Transactions */
      transactions: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  accounts_accounts_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountSummary"][];
        };
      };
    };
  };
  allocation_current_allocation_current_get: {
    parameters: {
      query?: {
        by?: components["schemas"]["AllocationDimension"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AllocationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  benchmarks_benchmarks_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BenchmarkInfo"][];
        };
      };
    };
  };
  benchmarks_daily_benchmarks_daily_get: {
    parameters: {
      query: {
        /** @description Instrument id from /benchmarks. */
        instrument_id: string;
        /** @description First day of the window (inclusive). Default: one year ago. */
        since?: string | null;
        /** @description Last day of the window (inclusive). Default: today. */
        until?: string | null;
        /** @description Page size. */
        limit?: number;
        /** @description Page start offset. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BenchmarkSeriesResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cashflow_daily_cashflow_daily_get: {
    parameters: {
      query?: {
        /** @description First day of the window (inclusive). Default: one year ago. */
        since?: string | null;
        /** @description Last day of the window (inclusive). Default: today. */
        until?: string | null;
        /** @description Filter to one account id. */
        account_id?: string | null;
        /** @description Filter to one entity id. */
        entity_id?: string | null;
        /** @description Page size. */
        limit?: number;
        /** @description Page start offset. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CashflowSeriesResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_connections_route_connections_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnectionListResponse"];
        };
      };
    };
  };
  list_aspsps_connections_aspsps_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AspspListResponse"];
        };
      };
    };
  };
  authorize_route_connections_authorize_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthorizeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConnectionOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  link_route_connections_link_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LinkRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LinkResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sync_route_connections__connection_id__sync_post: {
    parameters: {
      query?: {
        days?: number;
      };
      header?: never;
      path: {
        connection_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SyncResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_imports_imports_get: {
    parameters: {
      query?: {
        /** @description Page size. */
        limit?: number;
        /** @description Page start offset. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportSessionListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_import_imports_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_create_import_imports_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportSessionWithRows"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_import_imports__session_id__get: {
    parameters: {
      query?: {
        /** @description Page size. */
        limit?: number;
        /** @description Page start offset. */
        offset?: number;
      };
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportSessionWithRows"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  discard_import_imports__session_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportSessionOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  commit_import_imports__session_id__commit_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["CommitRequest"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommitResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_import_row_imports__session_id__rows__row_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
        row_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RowPatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportRowOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  suggest_import_mappings_imports__session_id__suggestions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuggestionsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  meta_freshness_meta_freshness_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FreshnessResponse"];
        };
      };
    };
  };
  net_worth_daily_net_worth_daily_get: {
    parameters: {
      query?: {
        /** @description First day of the window (inclusive). Default: one year ago. */
        since?: string | null;
        /** @description Last day of the window (inclusive). Default: today. */
        until?: string | null;
        /** @description Filter to one account id. */
        account_id?: string | null;
        /** @description Filter to one entity id. */
        entity_id?: string | null;
        group?: components["schemas"]["GroupBy"];
        /** @description Page size. */
        limit?: number;
        /** @description Page start offset. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["NetWorthSeriesResponse"]
            | components["schemas"]["NetWorthTotalSeriesResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  returns_daily_returns_daily_get: {
    parameters: {
      query?: {
        scope?: components["schemas"]["ReturnsScope"];
        /** @description Filter to one scope key (account id, asset-class key, or 'household'). */
        scope_key?: string | null;
        /** @description First day of the window (inclusive). Default: one year ago. */
        since?: string | null;
        /** @description Last day of the window (inclusive). Default: today. */
        until?: string | null;
        /** @description Page size. */
        limit?: number;
        /** @description Page start offset. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReturnsSeriesResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  returns_fees_returns_fees_get: {
    parameters: {
      query?: {
        /** @description First day of the window (inclusive). Default: one year ago. */
        since?: string | null;
        /** @description Last day of the window (inclusive). Default: today. */
        until?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeesResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  returns_summary_returns_summary_get: {
    parameters: {
      query?: {
        scope?: components["schemas"]["ReturnsScope"];
        /** @description First day of the window (inclusive). Default: one year ago. */
        since?: string | null;
        /** @description Last day of the window (inclusive). Default: today. */
        until?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReturnsSummaryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
