/** Runtime validation for read-API responses.
 *
 * Two layers keep the UI honest against the FastAPI contract:
 *
 * 1. `zod` schemas validate every payload at runtime (repo rule: never trust
 *    `JSON.parse` output untyped).
 * 2. The `_Check*` assertions below tie each inferred type to the types
 *    generated from the committed OpenAPI schema (`schema.d.ts`, generated by
 *    `openapi-typescript`), so schema drift fails the type-check.
 *
 * Decimal columns arrive as strings — see ADR-0035 and `money.ts`.
 */

import { z } from "zod";

import type { components } from "./schema";

type Generated = components["schemas"];

/** Decimal wire string, e.g. "1234.5600", "-0.25". */
const decimalString = z.string().regex(/^[+-]?(?:\d+\.?\d*|\.\d+)$/);

const isoDateString = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);

export const accountSummarySchema = z.object({
  account_id: z.string(),
  currency: z.string(),
  entity_id: z.string(),
  entity_name: z.string(),
  iban_masked: z.string(),
  kind: z.string(),
  name: z.string(),
  provider: z.string(),
});
export type AccountSummary = z.infer<typeof accountSummarySchema>;

export const accountsResponseSchema = z.array(accountSummarySchema);

export const allocationDimensionSchema = z.enum(["entity", "currency", "kind"]);
export type AllocationDimension = z.infer<typeof allocationDimensionSchema>;

export const allocationSliceSchema = z.object({
  balance_dkk: decimalString.nullable(),
  balance_eur: decimalString.nullable(),
  label: z.string(),
  weight_eur: decimalString.nullable(),
});
export type AllocationSlice = z.infer<typeof allocationSliceSchema>;

export const allocationResponseSchema = z.object({
  as_of: isoDateString.nullable(),
  by: allocationDimensionSchema,
  slices: z.array(allocationSliceSchema),
});
export type AllocationResponse = z.infer<typeof allocationResponseSchema>;

export const netWorthTotalPointSchema = z.object({
  as_of: isoDateString,
  balance_dkk: decimalString.nullable(),
  balance_eur: decimalString.nullable(),
});
export type NetWorthTotalPoint = z.infer<typeof netWorthTotalPointSchema>;

export const netWorthTotalSeriesResponseSchema = z.object({
  limit: z.number().int(),
  offset: z.number().int(),
  points: z.array(netWorthTotalPointSchema),
  total: z.number().int(),
});
export type NetWorthTotalSeriesResponse = z.infer<typeof netWorthTotalSeriesResponseSchema>;

export const netWorthPointSchema = z.object({
  account_currency: z.string(),
  account_id: z.string(),
  as_of: isoDateString,
  balance_acct_ccy: decimalString,
  balance_dkk: decimalString.nullable(),
  balance_eur: decimalString.nullable(),
  entity_id: z.string(),
});
export type NetWorthPoint = z.infer<typeof netWorthPointSchema>;

export const netWorthSeriesResponseSchema = z.object({
  limit: z.number().int(),
  offset: z.number().int(),
  points: z.array(netWorthPointSchema),
  total: z.number().int(),
});
export type NetWorthSeriesResponse = z.infer<typeof netWorthSeriesResponseSchema>;

export const cashflowPointSchema = z.object({
  account_currency: z.string(),
  account_id: z.string(),
  as_of: isoDateString,
  entity_id: z.string(),
  inflow_acct_ccy: decimalString,
  inflow_dkk: decimalString.nullable(),
  inflow_eur: decimalString.nullable(),
  net_acct_ccy: decimalString,
  net_dkk: decimalString.nullable(),
  net_eur: decimalString.nullable(),
  outflow_acct_ccy: decimalString,
  outflow_dkk: decimalString.nullable(),
  outflow_eur: decimalString.nullable(),
});
export type CashflowPoint = z.infer<typeof cashflowPointSchema>;

export const cashflowSeriesResponseSchema = z.object({
  limit: z.number().int(),
  offset: z.number().int(),
  points: z.array(cashflowPointSchema),
  total: z.number().int(),
});
export type CashflowSeriesResponse = z.infer<typeof cashflowSeriesResponseSchema>;

export const martFreshnessSchema = z.object({
  latest_as_of: isoDateString.nullable(),
  mart: z.string(),
  row_count: z.number().int(),
});
export type MartFreshness = z.infer<typeof martFreshnessSchema>;

export const freshnessResponseSchema = z.object({
  marts: z.array(martFreshnessSchema),
});
export type FreshnessResponse = z.infer<typeof freshnessResponseSchema>;

/* Compile-time contract checks: each zod-inferred type must stay mutually
 * assignable with the openapi-typescript generated type. A drifted schema
 * makes one of these aliases fail to type-check. */
type MutuallyAssignable<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;
type Assert<T extends true> = T;

type _CheckAccountSummary = Assert<MutuallyAssignable<AccountSummary, Generated["AccountSummary"]>>;
type _CheckAllocationDimension = Assert<
  MutuallyAssignable<AllocationDimension, Generated["AllocationDimension"]>
>;
type _CheckAllocationSlice = Assert<
  MutuallyAssignable<AllocationSlice, Generated["AllocationSlice"]>
>;
type _CheckAllocationResponse = Assert<
  MutuallyAssignable<AllocationResponse, Generated["AllocationResponse"]>
>;
type _CheckNetWorthTotalPoint = Assert<
  MutuallyAssignable<NetWorthTotalPoint, Generated["NetWorthTotalPoint"]>
>;
type _CheckNetWorthTotalSeries = Assert<
  MutuallyAssignable<NetWorthTotalSeriesResponse, Generated["NetWorthTotalSeriesResponse"]>
>;
type _CheckNetWorthPoint = Assert<MutuallyAssignable<NetWorthPoint, Generated["NetWorthPoint"]>>;
type _CheckNetWorthSeries = Assert<
  MutuallyAssignable<NetWorthSeriesResponse, Generated["NetWorthSeriesResponse"]>
>;
type _CheckCashflowPoint = Assert<MutuallyAssignable<CashflowPoint, Generated["CashflowPoint"]>>;
type _CheckCashflowSeries = Assert<
  MutuallyAssignable<CashflowSeriesResponse, Generated["CashflowSeriesResponse"]>
>;
type _CheckMartFreshness = Assert<MutuallyAssignable<MartFreshness, Generated["MartFreshness"]>>;
type _CheckFreshnessResponse = Assert<
  MutuallyAssignable<FreshnessResponse, Generated["FreshnessResponse"]>
>;
