/** Runtime validation for read-API responses.
 *
 * Two layers keep the UI honest against the FastAPI contract:
 *
 * 1. `zod` schemas validate every payload at runtime (repo rule: never trust
 *    `JSON.parse` output untyped).
 * 2. The `_Check*` assertions below tie each inferred type to the types
 *    generated from the committed OpenAPI schema (`schema.d.ts`, generated by
 *    `openapi-typescript`), so schema drift fails the type-check.
 *
 * Decimal columns arrive as strings — see ADR-0035 and `money.ts`.
 */

import { z } from "zod";

import type { components } from "./schema";

type Generated = components["schemas"];

/** Decimal wire string, e.g. "1234.5600", "-0.25". */
const decimalString = z.string().regex(/^[+-]?(?:\d+\.?\d*|\.\d+)$/);

const isoDateString = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);

export const accountSummarySchema = z.object({
  account_id: z.string(),
  currency: z.string(),
  entity_id: z.string(),
  entity_name: z.string(),
  iban_masked: z.string(),
  kind: z.string(),
  name: z.string(),
  provider: z.string(),
});
export type AccountSummary = z.infer<typeof accountSummarySchema>;

export const accountsResponseSchema = z.array(accountSummarySchema);

export const allocationDimensionSchema = z.enum(["entity", "currency", "kind"]);
export type AllocationDimension = z.infer<typeof allocationDimensionSchema>;

export const allocationSliceSchema = z.object({
  balance_dkk: decimalString.nullable(),
  balance_eur: decimalString.nullable(),
  label: z.string(),
  weight_eur: decimalString.nullable(),
});
export type AllocationSlice = z.infer<typeof allocationSliceSchema>;

export const allocationResponseSchema = z.object({
  as_of: isoDateString.nullable(),
  by: allocationDimensionSchema,
  slices: z.array(allocationSliceSchema),
});
export type AllocationResponse = z.infer<typeof allocationResponseSchema>;

export const netWorthTotalPointSchema = z.object({
  as_of: isoDateString,
  balance_dkk: decimalString.nullable(),
  balance_eur: decimalString.nullable(),
});
export type NetWorthTotalPoint = z.infer<typeof netWorthTotalPointSchema>;

export const netWorthTotalSeriesResponseSchema = z.object({
  limit: z.number().int(),
  offset: z.number().int(),
  points: z.array(netWorthTotalPointSchema),
  total: z.number().int(),
});
export type NetWorthTotalSeriesResponse = z.infer<typeof netWorthTotalSeriesResponseSchema>;

export const netWorthPointSchema = z.object({
  account_currency: z.string(),
  account_id: z.string(),
  as_of: isoDateString,
  balance_acct_ccy: decimalString,
  balance_dkk: decimalString.nullable(),
  balance_eur: decimalString.nullable(),
  entity_id: z.string(),
});
export type NetWorthPoint = z.infer<typeof netWorthPointSchema>;

export const netWorthSeriesResponseSchema = z.object({
  limit: z.number().int(),
  offset: z.number().int(),
  points: z.array(netWorthPointSchema),
  total: z.number().int(),
});
export type NetWorthSeriesResponse = z.infer<typeof netWorthSeriesResponseSchema>;

export const cashflowPointSchema = z.object({
  account_currency: z.string(),
  account_id: z.string(),
  as_of: isoDateString,
  entity_id: z.string(),
  inflow_acct_ccy: decimalString,
  inflow_dkk: decimalString.nullable(),
  inflow_eur: decimalString.nullable(),
  net_acct_ccy: decimalString,
  net_dkk: decimalString.nullable(),
  net_eur: decimalString.nullable(),
  outflow_acct_ccy: decimalString,
  outflow_dkk: decimalString.nullable(),
  outflow_eur: decimalString.nullable(),
});
export type CashflowPoint = z.infer<typeof cashflowPointSchema>;

export const cashflowSeriesResponseSchema = z.object({
  limit: z.number().int(),
  offset: z.number().int(),
  points: z.array(cashflowPointSchema),
  total: z.number().int(),
});
export type CashflowSeriesResponse = z.infer<typeof cashflowSeriesResponseSchema>;

export const martFreshnessSchema = z.object({
  latest_as_of: isoDateString.nullable(),
  mart: z.string(),
  row_count: z.number().int(),
});
export type MartFreshness = z.infer<typeof martFreshnessSchema>;

export const freshnessResponseSchema = z.object({
  marts: z.array(martFreshnessSchema),
});
export type FreshnessResponse = z.infer<typeof freshnessResponseSchema>;

/* ---- returns, benchmarks, fees (#206) ---- */

export const returnsScopeSchema = z.enum(["account", "asset_class", "household"]);
export type ReturnsScope = z.infer<typeof returnsScopeSchema>;

export const returnsPointSchema = z.object({
  as_of: isoDateString,
  begin_mv_dkk: decimalString.nullable(),
  begin_mv_eur: decimalString.nullable(),
  end_mv_dkk: decimalString.nullable(),
  end_mv_eur: decimalString.nullable(),
  net_flow_dkk: decimalString.nullable(),
  net_flow_eur: decimalString.nullable(),
  return_factor_dkk: decimalString.nullable(),
  return_factor_eur: decimalString.nullable(),
  scope: returnsScopeSchema,
  scope_key: z.string(),
});
export type ReturnsPoint = z.infer<typeof returnsPointSchema>;

export const returnsSeriesResponseSchema = z.object({
  limit: z.number().int(),
  offset: z.number().int(),
  points: z.array(returnsPointSchema),
  total: z.number().int(),
});
export type ReturnsSeriesResponse = z.infer<typeof returnsSeriesResponseSchema>;

export const currencyReturnSummarySchema = z.object({
  annualized_return: z.number().nullable(),
  cumulative_return: decimalString.nullable(),
  error: z.string().nullable(),
  mwr_annualized: z.number().nullable(),
});
export type CurrencyReturnSummary = z.infer<typeof currencyReturnSummarySchema>;

export const returnsSummaryEntrySchema = z.object({
  days: z.number().int(),
  dkk: currencyReturnSummarySchema,
  end_date: isoDateString.nullable(),
  eur: currencyReturnSummarySchema,
  scope: returnsScopeSchema,
  scope_key: z.string(),
  start_date: isoDateString.nullable(),
});
export type ReturnsSummaryEntry = z.infer<typeof returnsSummaryEntrySchema>;

export const returnsSummaryResponseSchema = z.object({
  entries: z.array(returnsSummaryEntrySchema),
  scope: returnsScopeSchema,
  since: isoDateString,
  until: isoDateString,
});
export type ReturnsSummaryResponse = z.infer<typeof returnsSummaryResponseSchema>;

export const benchmarkInfoSchema = z.object({
  currency: z.string(),
  first_as_of: isoDateString.nullable(),
  instrument_id: z.string(),
  last_as_of: isoDateString.nullable(),
  name: z.string(),
  points: z.number().int(),
  ticker: z.string().nullable(),
});
export type BenchmarkInfo = z.infer<typeof benchmarkInfoSchema>;

export const benchmarksResponseSchema = z.array(benchmarkInfoSchema);

export const benchmarkPointSchema = z.object({
  as_of: isoDateString,
  close: decimalString,
  currency: z.string(),
});
export type BenchmarkPoint = z.infer<typeof benchmarkPointSchema>;

export const benchmarkSeriesResponseSchema = z.object({
  instrument_id: z.string(),
  limit: z.number().int(),
  offset: z.number().int(),
  points: z.array(benchmarkPointSchema),
  total: z.number().int(),
});
export type BenchmarkSeriesResponse = z.infer<typeof benchmarkSeriesResponseSchema>;

export const feeYearRowSchema = z.object({
  account_id: z.string(),
  fees_dkk: decimalString.nullable(),
  fees_eur: decimalString.nullable(),
  year: z.number().int(),
});
export type FeeYearRow = z.infer<typeof feeYearRowSchema>;

export const feesResponseSchema = z.object({
  rows: z.array(feeYearRowSchema),
  since: isoDateString,
  until: isoDateString,
});
export type FeesResponse = z.infer<typeof feesResponseSchema>;

/* ---- import sessions (#207/#208) ---- */

const isoTimestampString = z.string();

export const rowIssueSchema = z.object({
  code: z.string(),
  detail: z.string(),
});
export type RowIssue = z.infer<typeof rowIssueSchema>;

export const rowCountsSchema = z.object({
  error: z.number().int(),
  excluded: z.number().int(),
  ok: z.number().int(),
  total: z.number().int(),
  warning: z.number().int(),
});
export type RowCounts = z.infer<typeof rowCountsSchema>;

export const importRowSchema = z.object({
  accepted_at: isoTimestampString.nullable(),
  edited: z.boolean(),
  excluded: z.boolean(),
  id: z.string(),
  issues: z.array(rowIssueSchema),
  kind: z.string(),
  mappings: z.record(z.string(), z.string()),
  payload: z.record(z.string(), z.unknown()),
  row_index: z.number().int(),
  status: z.string(),
  suggested_by: z.string().nullable(),
});
export type ImportRow = z.infer<typeof importRowSchema>;

const importSessionShape = {
  committed_at: isoTimestampString.nullable(),
  content_sha256: z.string(),
  created_at: isoTimestampString,
  error: z.string().nullable(),
  expires_at: isoTimestampString,
  id: z.string(),
  original_filename: z.string(),
  params: z.record(z.string(), z.unknown()),
  row_counts: rowCountsSchema,
  source: z.string(),
  status: z.string(),
  updated_at: isoTimestampString,
} as const;

export const importSessionSchema = z.object(importSessionShape);
export type ImportSession = z.infer<typeof importSessionSchema>;

export const importSessionWithRowsSchema = z.object({
  ...importSessionShape,
  rows: z.array(importRowSchema),
  total_rows: z.number().int(),
});
export type ImportSessionWithRows = z.infer<typeof importSessionWithRowsSchema>;

export const importSessionListSchema = z.object({
  sessions: z.array(importSessionSchema),
  total: z.number().int(),
});
export type ImportSessionList = z.infer<typeof importSessionListSchema>;

export const commitCountsSchema = z.object({
  accounts: z.number().int(),
  entities: z.number().int(),
  holding_snapshots: z.number().int(),
  instruments: z.number().int(),
  transactions: z.number().int(),
});
export type CommitCounts = z.infer<typeof commitCountsSchema>;

export const commitResponseSchema = z.object({
  counts: commitCountsSchema,
  session: importSessionSchema,
});
export type CommitResponse = z.infer<typeof commitResponseSchema>;

export const mappingSuggestionSchema = z.object({
  confidence: z.number(),
  field: z.string(),
  kind: z.string(),
  reason: z.string(),
  row_id: z.string(),
  row_index: z.number().int(),
  value: z.string(),
});
export type MappingSuggestion = z.infer<typeof mappingSuggestionSchema>;

export const suggestionSessionSchema = z.object({
  id: z.string(),
  rows_considered: z.number().int(),
  source: z.string(),
  status: z.string(),
});
export type SuggestionSession = z.infer<typeof suggestionSessionSchema>;

export const suggestionsResponseSchema = z.object({
  session: suggestionSessionSchema,
  suggested_by: z.string(),
  suggestions: z.array(mappingSuggestionSchema),
});
export type SuggestionsResponse = z.infer<typeof suggestionsResponseSchema>;

/* ---- bank connections (Enable Banking, #230) ---- */

export const aspspSchema = z.object({
  aspsp_country: z.string(),
  aspsp_name: z.string(),
  default_currency: z.string(),
  provider: z.string(),
});
export type Aspsp = z.infer<typeof aspspSchema>;

export const aspspListResponseSchema = z.object({
  providers: z.array(aspspSchema),
});
export type AspspListResponse = z.infer<typeof aspspListResponseSchema>;

export const connectionAccountSchema = z.object({
  currency: z.string().nullable(),
  iban_masked: z.string().nullable(),
  name: z.string().nullable(),
  product: z.string().nullable(),
});
export type ConnectionAccount = z.infer<typeof connectionAccountSchema>;

export const connectionErrorSchema = z.object({
  at: z.string(),
  code: z.string().nullable(),
  message: z.string(),
  status_code: z.number().int().nullable(),
  step: z.string(),
});
export type ConnectionError = z.infer<typeof connectionErrorSchema>;

export const connectionSchema = z.object({
  accounts: z.array(connectionAccountSchema),
  aspsp_country: z.string(),
  aspsp_name: z.string(),
  created_at: z.string(),
  entity_name: z.string(),
  id: z.string(),
  last_error: connectionErrorSchema.nullable(),
  last_sync_at: z.string().nullable(),
  last_sync_status: z.string().nullable(),
  provider: z.string(),
  status: z.string(),
  updated_at: z.string(),
  valid_until: z.string().nullable(),
});
export type Connection = z.infer<typeof connectionSchema>;

export const connectionListResponseSchema = z.object({
  connections: z.array(connectionSchema),
});
export type ConnectionListResponse = z.infer<typeof connectionListResponseSchema>;

export const linkResponseSchema = z.object({
  connection_id: z.string(),
  consent_url: z.string(),
  state: z.string(),
  valid_until: z.string(),
});
export type LinkResponse = z.infer<typeof linkResponseSchema>;

export const syncResponseSchema = z.object({
  connection: connectionSchema,
  holding_snapshots: z.number().int(),
  transactions: z.number().int(),
});
export type SyncResponse = z.infer<typeof syncResponseSchema>;

/* Compile-time contract checks: each zod-inferred type must stay mutually
 * assignable with the openapi-typescript generated type. A drifted schema
 * makes one of these aliases fail to type-check. */
type MutuallyAssignable<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;
type Assert<T extends true> = T;

type _CheckAccountSummary = Assert<MutuallyAssignable<AccountSummary, Generated["AccountSummary"]>>;
type _CheckAllocationDimension = Assert<
  MutuallyAssignable<AllocationDimension, Generated["AllocationDimension"]>
>;
type _CheckAllocationSlice = Assert<
  MutuallyAssignable<AllocationSlice, Generated["AllocationSlice"]>
>;
type _CheckAllocationResponse = Assert<
  MutuallyAssignable<AllocationResponse, Generated["AllocationResponse"]>
>;
type _CheckNetWorthTotalPoint = Assert<
  MutuallyAssignable<NetWorthTotalPoint, Generated["NetWorthTotalPoint"]>
>;
type _CheckNetWorthTotalSeries = Assert<
  MutuallyAssignable<NetWorthTotalSeriesResponse, Generated["NetWorthTotalSeriesResponse"]>
>;
type _CheckNetWorthPoint = Assert<MutuallyAssignable<NetWorthPoint, Generated["NetWorthPoint"]>>;
type _CheckNetWorthSeries = Assert<
  MutuallyAssignable<NetWorthSeriesResponse, Generated["NetWorthSeriesResponse"]>
>;
type _CheckCashflowPoint = Assert<MutuallyAssignable<CashflowPoint, Generated["CashflowPoint"]>>;
type _CheckCashflowSeries = Assert<
  MutuallyAssignable<CashflowSeriesResponse, Generated["CashflowSeriesResponse"]>
>;
type _CheckMartFreshness = Assert<MutuallyAssignable<MartFreshness, Generated["MartFreshness"]>>;
type _CheckFreshnessResponse = Assert<
  MutuallyAssignable<FreshnessResponse, Generated["FreshnessResponse"]>
>;
type _CheckRowIssue = Assert<MutuallyAssignable<RowIssue, Generated["RowIssue"]>>;
type _CheckRowCounts = Assert<MutuallyAssignable<RowCounts, Generated["RowCounts"]>>;
type _CheckImportRow = Assert<MutuallyAssignable<ImportRow, Generated["ImportRowOut"]>>;
type _CheckImportSession = Assert<MutuallyAssignable<ImportSession, Generated["ImportSessionOut"]>>;
type _CheckImportSessionWithRows = Assert<
  MutuallyAssignable<ImportSessionWithRows, Generated["ImportSessionWithRows"]>
>;
type _CheckImportSessionList = Assert<
  MutuallyAssignable<ImportSessionList, Generated["ImportSessionListResponse"]>
>;
type _CheckCommitCounts = Assert<MutuallyAssignable<CommitCounts, Generated["CommitCountsOut"]>>;
type _CheckCommitResponse = Assert<MutuallyAssignable<CommitResponse, Generated["CommitResponse"]>>;
type _CheckMappingSuggestion = Assert<
  MutuallyAssignable<MappingSuggestion, Generated["MappingSuggestionOut"]>
>;
type _CheckSuggestionSession = Assert<
  MutuallyAssignable<SuggestionSession, Generated["SuggestionSessionOut"]>
>;
type _CheckSuggestionsResponse = Assert<
  MutuallyAssignable<SuggestionsResponse, Generated["SuggestionsResponse"]>
>;
type _CheckReturnsScope = Assert<MutuallyAssignable<ReturnsScope, Generated["ReturnsScope"]>>;
type _CheckReturnsPoint = Assert<MutuallyAssignable<ReturnsPoint, Generated["ReturnsPoint"]>>;
type _CheckReturnsSeries = Assert<
  MutuallyAssignable<ReturnsSeriesResponse, Generated["ReturnsSeriesResponse"]>
>;
type _CheckCurrencyReturnSummary = Assert<
  MutuallyAssignable<CurrencyReturnSummary, Generated["CurrencyReturnSummary"]>
>;
type _CheckReturnsSummaryEntry = Assert<
  MutuallyAssignable<ReturnsSummaryEntry, Generated["ReturnsSummaryEntry"]>
>;
type _CheckReturnsSummaryResponse = Assert<
  MutuallyAssignable<ReturnsSummaryResponse, Generated["ReturnsSummaryResponse"]>
>;
type _CheckBenchmarkInfo = Assert<MutuallyAssignable<BenchmarkInfo, Generated["BenchmarkInfo"]>>;
type _CheckBenchmarkPoint = Assert<MutuallyAssignable<BenchmarkPoint, Generated["BenchmarkPoint"]>>;
type _CheckBenchmarkSeries = Assert<
  MutuallyAssignable<BenchmarkSeriesResponse, Generated["BenchmarkSeriesResponse"]>
>;
type _CheckFeeYearRow = Assert<MutuallyAssignable<FeeYearRow, Generated["FeeYearRow"]>>;
type _CheckFeesResponse = Assert<MutuallyAssignable<FeesResponse, Generated["FeesResponse"]>>;
type _CheckAspsp = Assert<MutuallyAssignable<Aspsp, Generated["AspspOut"]>>;
type _CheckAspspListResponse = Assert<
  MutuallyAssignable<AspspListResponse, Generated["AspspListResponse"]>
>;
type _CheckConnectionAccount = Assert<
  MutuallyAssignable<ConnectionAccount, Generated["ConnectionAccountOut"]>
>;
type _CheckConnectionError = Assert<
  MutuallyAssignable<ConnectionError, Generated["ConnectionErrorOut"]>
>;
type _CheckConnection = Assert<MutuallyAssignable<Connection, Generated["ConnectionOut"]>>;
type _CheckConnectionListResponse = Assert<
  MutuallyAssignable<ConnectionListResponse, Generated["ConnectionListResponse"]>
>;
type _CheckLinkResponse = Assert<MutuallyAssignable<LinkResponse, Generated["LinkResponse"]>>;
type _CheckSyncResponse = Assert<MutuallyAssignable<SyncResponse, Generated["SyncResponse"]>>;
