/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/accounts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Accounts
     * @description Account dimension with IBAN and name suffix masked server-side.
     */
    get: operations["accounts_accounts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/allocation/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Allocation Current
     * @description Latest-day allocation grouped by entity, currency, or account kind.
     */
    get: operations["allocation_current_allocation_current_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cashflow/daily": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cashflow Daily
     * @description Daily cashflow series per account (absent days mean zero).
     */
    get: operations["cashflow_daily_cashflow_daily_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/imports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Imports
     * @description List import sessions, newest first.
     */
    get: operations["list_imports_imports_get"];
    put?: never;
    /**
     * Create Import
     * @description Upload one statement, parse it, and stage its rows for review.
     */
    post: operations["create_import_imports_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/imports/{session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Import
     * @description Return one session with one page of its staged rows.
     */
    get: operations["get_import_imports__session_id__get"];
    put?: never;
    post?: never;
    /**
     * Discard Import
     * @description Discard a staged (or expired) session and delete its stored file.
     */
    delete: operations["discard_import_imports__session_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/imports/{session_id}/commit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Commit Import
     * @description Write all included rows to the raw tables via the loaders.
     */
    post: operations["commit_import_imports__session_id__commit_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/imports/{session_id}/rows/{row_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Patch Import Row
     * @description Correct or exclude one staged row before commit.
     */
    patch: operations["patch_import_row_imports__session_id__rows__row_id__patch"];
    trace?: never;
  };
  "/meta/freshness": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Meta Freshness
     * @description Latest data date and row count per mart, for staleness banners.
     */
    get: operations["meta_freshness_meta_freshness_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/net-worth/daily": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Net Worth Daily
     * @description Daily net-worth series, per account or summed per day.
     */
    get: operations["net_worth_daily_net_worth_daily_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AccountSummary
     * @description Account dimension row with identifiers masked server-side.
     *
     *     ``iban_masked`` keeps only the last four characters
     *     (``penge.web.mask.mask_iban``); the raw IBAN never leaves the API.
     */
    AccountSummary: {
      /** Account Id */
      account_id: string;
      /** Currency */
      currency: string;
      /** Entity Id */
      entity_id: string;
      /** Entity Name */
      entity_name: string;
      /** Iban Masked */
      iban_masked: string;
      /** Kind */
      kind: string;
      /** Name */
      name: string;
      /** Provider */
      provider: string;
    };
    /**
     * AllocationDimension
     * @description Grouping dimension for the current-allocation endpoint.
     * @enum {string}
     */
    AllocationDimension: "entity" | "currency" | "kind";
    /**
     * AllocationResponse
     * @description Current allocation snapshot grouped by one dimension.
     */
    AllocationResponse: {
      /** As Of */
      as_of: string | null;
      by: components["schemas"]["AllocationDimension"];
      /** Slices */
      slices: components["schemas"]["AllocationSlice"][];
    };
    /**
     * AllocationSlice
     * @description One slice of the latest-day allocation, grouped by a dimension.
     *
     *     ``weight_eur`` is this slice's share of the EUR total (0..1);
     *     ``None`` when the EUR total is zero or missing.
     */
    AllocationSlice: {
      /** Balance Dkk */
      balance_dkk: string | null;
      /** Balance Eur */
      balance_eur: string | null;
      /** Label */
      label: string;
      /** Weight Eur */
      weight_eur: string | null;
    };
    /** Body_create_import_imports_post */
    Body_create_import_imports_post: {
      /** Account Name */
      account_name?: string | null;
      /** Entity Name */
      entity_name?: string | null;
      /** File */
      file: string;
      /** Source */
      source?: string | null;
    };
    /**
     * CashflowPoint
     * @description One account-day row of ``mart_cashflow_daily``.
     *
     *     Days without transactions produce no row; consumers treat absent
     *     days as zero (same contract as the MCP ``query_cashflow`` tool).
     */
    CashflowPoint: {
      /** Account Currency */
      account_currency: string;
      /** Account Id */
      account_id: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Entity Id */
      entity_id: string;
      /** Inflow Acct Ccy */
      inflow_acct_ccy: string;
      /** Inflow Dkk */
      inflow_dkk: string | null;
      /** Inflow Eur */
      inflow_eur: string | null;
      /** Net Acct Ccy */
      net_acct_ccy: string;
      /** Net Dkk */
      net_dkk: string | null;
      /** Net Eur */
      net_eur: string | null;
      /** Outflow Acct Ccy */
      outflow_acct_ccy: string;
      /** Outflow Dkk */
      outflow_dkk: string | null;
      /** Outflow Eur */
      outflow_eur: string | null;
    };
    /**
     * CashflowSeriesResponse
     * @description Paginated cashflow series at account granularity.
     */
    CashflowSeriesResponse: {
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Points */
      points: components["schemas"]["CashflowPoint"][];
      /** Total */
      total: number;
    };
    /**
     * CommitCountsOut
     * @description Rows written by a commit, in loader vocabulary.
     */
    CommitCountsOut: {
      /** Accounts */
      accounts: number;
      /** Entities */
      entities: number;
      /** Holding Snapshots */
      holding_snapshots: number;
      /** Instruments */
      instruments: number;
      /** Transactions */
      transactions: number;
    };
    /**
     * CommitRequest
     * @description Optional commit-time parameters (override upload-time values).
     */
    CommitRequest: {
      /** Account Name */
      account_name?: string | null;
      /** Entity Name */
      entity_name?: string | null;
    };
    /**
     * CommitResponse
     * @description Result of committing a session.
     */
    CommitResponse: {
      counts: components["schemas"]["CommitCountsOut"];
      session: components["schemas"]["ImportSessionOut"];
    };
    /**
     * FreshnessResponse
     * @description Freshness metadata for every mart the API serves.
     */
    FreshnessResponse: {
      /** Marts */
      marts: components["schemas"]["MartFreshness"][];
    };
    /**
     * GroupBy
     * @description Aggregation level for the net-worth series.
     * @enum {string}
     */
    GroupBy: "account" | "total";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * ImportRowOut
     * @description One staged row of an import session.
     */
    ImportRowOut: {
      /** Edited */
      edited: boolean;
      /** Excluded */
      excluded: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Issues */
      issues: components["schemas"]["RowIssue"][];
      /** Kind */
      kind: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /** Row Index */
      row_index: number;
      /** Status */
      status: string;
    };
    /**
     * ImportSessionListResponse
     * @description One page of import sessions, newest first.
     */
    ImportSessionListResponse: {
      /** Sessions */
      sessions: components["schemas"]["ImportSessionOut"][];
      /** Total */
      total: number;
    };
    /**
     * ImportSessionOut
     * @description One import session without its rows.
     */
    ImportSessionOut: {
      /** Committed At */
      committed_at: string | null;
      /** Content Sha256 */
      content_sha256: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error */
      error: string | null;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Original Filename */
      original_filename: string;
      /** Params */
      params: {
        [key: string]: unknown;
      };
      row_counts: components["schemas"]["RowCounts"];
      /** Source */
      source: string;
      /** Status */
      status: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ImportSessionWithRows
     * @description One import session plus one page of its rows.
     */
    ImportSessionWithRows: {
      /** Committed At */
      committed_at: string | null;
      /** Content Sha256 */
      content_sha256: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error */
      error: string | null;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Original Filename */
      original_filename: string;
      /** Params */
      params: {
        [key: string]: unknown;
      };
      row_counts: components["schemas"]["RowCounts"];
      /** Rows */
      rows: components["schemas"]["ImportRowOut"][];
      /** Source */
      source: string;
      /** Status */
      status: string;
      /** Total Rows */
      total_rows: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * MartFreshness
     * @description Latest data date and row count for one mart.
     */
    MartFreshness: {
      /** Latest As Of */
      latest_as_of: string | null;
      /** Mart */
      mart: string;
      /** Row Count */
      row_count: number;
    };
    /**
     * NetWorthPoint
     * @description One account-day row of ``mart_net_worth_daily``.
     */
    NetWorthPoint: {
      /** Account Currency */
      account_currency: string;
      /** Account Id */
      account_id: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Balance Acct Ccy */
      balance_acct_ccy: string;
      /** Balance Dkk */
      balance_dkk: string | null;
      /** Balance Eur */
      balance_eur: string | null;
      /** Entity Id */
      entity_id: string;
    };
    /**
     * NetWorthSeriesResponse
     * @description Paginated net-worth series at account granularity.
     */
    NetWorthSeriesResponse: {
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Points */
      points: components["schemas"]["NetWorthPoint"][];
      /** Total */
      total: number;
    };
    /**
     * NetWorthTotalPoint
     * @description One day of the net-worth series summed across all accounts.
     */
    NetWorthTotalPoint: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Balance Dkk */
      balance_dkk: string | null;
      /** Balance Eur */
      balance_eur: string | null;
    };
    /**
     * NetWorthTotalSeriesResponse
     * @description Net-worth series aggregated to one row per day.
     */
    NetWorthTotalSeriesResponse: {
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Points */
      points: components["schemas"]["NetWorthTotalPoint"][];
      /** Total */
      total: number;
    };
    /**
     * RowCounts
     * @description Aggregated review state of a session's rows.
     */
    RowCounts: {
      /** Error */
      error: number;
      /** Excluded */
      excluded: number;
      /** Ok */
      ok: number;
      /** Total */
      total: number;
      /** Warning */
      warning: number;
    };
    /**
     * RowIssue
     * @description One validation or duplicate finding on a staged row.
     */
    RowIssue: {
      /** Code */
      code: string;
      /** Detail */
      detail: string;
    };
    /**
     * RowPatchRequest
     * @description Corrections to one staged row before commit.
     */
    RowPatchRequest: {
      /** Excluded */
      excluded?: boolean | null;
      /** Payload */
      payload?: {
        [key: string]: unknown;
      } | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  accounts_accounts_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountSummary"][];
        };
      };
    };
  };
  allocation_current_allocation_current_get: {
    parameters: {
      query?: {
        by?: components["schemas"]["AllocationDimension"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AllocationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cashflow_daily_cashflow_daily_get: {
    parameters: {
      query?: {
        /** @description First day of the window (inclusive). Default: one year ago. */
        since?: string | null;
        /** @description Last day of the window (inclusive). Default: today. */
        until?: string | null;
        /** @description Filter to one account id. */
        account_id?: string | null;
        /** @description Filter to one entity id. */
        entity_id?: string | null;
        /** @description Page size. */
        limit?: number;
        /** @description Page start offset. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CashflowSeriesResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_imports_imports_get: {
    parameters: {
      query?: {
        /** @description Page size. */
        limit?: number;
        /** @description Page start offset. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportSessionListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_import_imports_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_create_import_imports_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportSessionWithRows"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_import_imports__session_id__get: {
    parameters: {
      query?: {
        /** @description Page size. */
        limit?: number;
        /** @description Page start offset. */
        offset?: number;
      };
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportSessionWithRows"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  discard_import_imports__session_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportSessionOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  commit_import_imports__session_id__commit_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["CommitRequest"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommitResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_import_row_imports__session_id__rows__row_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
        row_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RowPatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportRowOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  meta_freshness_meta_freshness_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FreshnessResponse"];
        };
      };
    };
  };
  net_worth_daily_net_worth_daily_get: {
    parameters: {
      query?: {
        /** @description First day of the window (inclusive). Default: one year ago. */
        since?: string | null;
        /** @description Last day of the window (inclusive). Default: today. */
        until?: string | null;
        /** @description Filter to one account id. */
        account_id?: string | null;
        /** @description Filter to one entity id. */
        entity_id?: string | null;
        group?: components["schemas"]["GroupBy"];
        /** @description Page size. */
        limit?: number;
        /** @description Page start offset. */
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["NetWorthSeriesResponse"]
            | components["schemas"]["NetWorthTotalSeriesResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
