"""JSON CLI wrapper around the Penge tax calculators (issue #49).

Stable contract used by the MCP `compute_tax_year` tool. Reads a JSON
specification of the household's holdings for one tax year and writes
a JSON tax report to stdout. The contract is deliberately minimal so
the same shape can be regenerated by a future ingestion-driven flow
without breaking the MCP wire schema.

Invocation::

    python -m penge.tax.cli \\
        --year 2024 \\
        --currency EUR \\
        --jurisdictions DK,DE \\
        --input path/to/spec.json

If ``--input`` is omitted, the CLI looks for
``${PENGE_TAX_INPUTS_DIR:-data/tax}/<year>.json`` and treats the
holdings as empty when that file does not exist (the report then has
zero line items and zero totals — useful as a safe default).

If ``--input -`` is passed, the JSON spec is read from stdin.

Input schema (all keys optional)::

    {
      "fx": {"DKK_to_EUR": "0.134", "EUR_to_DKK": "7.46"},
      "dk": {
        "lager": [LagerInput, ...],
        "ask":   [{"account_id": str, "lager": [LagerInput, ...]}],
        "pal":   [PalInput, ...],
        "prior_loss_carry_forward": "<DKK decimal>"
      },
      "de": {
        "vorab": [VorabInput, ...]
      }
    }

Output schema (matches the MCP wire schema)::

    [
      {
        "year": 2024,
        "jurisdiction": "DK" | "DE",
        "currency": "EUR" | "DKK",
        "summary": {<jurisdiction-specific totals>},
        "line_items": [
          {"category": str, "amount": float, "source": str}, ...
        ]
      },
      ...
    ]

Money amounts in the output are floats in the requested ``currency``;
native amounts (DKK for DK, EUR for DE) are converted via the supplied
``fx`` map when the requested currency differs. Missing fx for a
required conversion is a hard error.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections.abc import Iterable, Mapping
from decimal import ROUND_HALF_EVEN, Decimal
from pathlib import Path
from typing import Any, Literal, cast

from pydantic import ValidationError

from penge.tax.aktiesparekonto import AskTaxResult, compute_ask_taxes
from penge.tax.de_vorab import VorabInput, VorabResult, compute_vorabpauschale
from penge.tax.lager import (
    BuyLeg,
    Distribution,
    LagerInput,
    LagerResult,
    SellLeg,
    compute_lager,
)
from penge.tax.lots import Money
from penge.tax.pal import (
    PalContribution,
    PalInput,
    PalResult,
    PalWithdrawal,
    compute_pal,
)
from penge.tax.report_dk import build_skat_report

__all__ = ["main"]

Jurisdiction = Literal["DK", "DE"]
Currency = Literal["EUR", "DKK"]

_MONEY_DP = Decimal("0.01")


class CliError(Exception):
    """Raised on invalid CLI arguments or input JSON."""


def _q(value: Decimal) -> Decimal:
    return value.quantize(_MONEY_DP, rounding=ROUND_HALF_EVEN)


def _money(amount: str | int | float | Decimal, currency: Currency) -> Money:
    return Money(amount=Decimal(str(amount)), currency=currency)


def _safe_decode(label: str, raw: Any, fn: Any) -> Any:
    """Run a decode helper and convert shape errors into CliError.

    Required-key/wrong-type problems in the input file should surface
    as deterministic input errors (exit code 2 with a stable message),
    not as the generic last-resort `Exception` path.
    """
    if not isinstance(raw, Mapping):
        raise CliError(f"invalid {label}: expected an object, got {type(raw).__name__}")
    try:
        return fn(raw)
    except KeyError as exc:
        raise CliError(f"invalid {label}: missing required key {exc.args[0]!r}") from exc
    except ValidationError:
        # Let main()'s ValidationError handler format these — it strips
        # offending input values to avoid leaking PII into audit logs.
        raise
    except (TypeError, ValueError) as exc:
        raise CliError(f"invalid {label}: {exc}") from exc


def _decode_lager(raw: Mapping[str, Any]) -> LagerInput:
    def _do(r: Mapping[str, Any]) -> LagerInput:
        return LagerInput(
            account_id=str(r["account_id"]),
            isin=str(r["isin"]),
            tax_year=int(r["tax_year"]),
            start_market_value=_money(r["start_market_value"], "DKK"),
            end_market_value=_money(r["end_market_value"], "DKK"),
            buys=tuple(BuyLeg(cost=_money(b["cost"], "DKK")) for b in r.get("buys", [])),
            sells=tuple(SellLeg(proceeds=_money(s["proceeds"], "DKK")) for s in r.get("sells", [])),
            distributions=tuple(
                Distribution(amount=_money(d["amount"], "DKK")) for d in r.get("distributions", [])
            ),
        )

    return cast(LagerInput, _safe_decode("lager input", raw, _do))


def _decode_pal(raw: Mapping[str, Any]) -> PalInput:
    def _do(r: Mapping[str, Any]) -> PalInput:
        return PalInput(
            account_id=str(r["account_id"]),
            tax_year=int(r["tax_year"]),
            start_market_value=_money(r["start_market_value"], "DKK"),
            end_market_value=_money(r["end_market_value"], "DKK"),
            contributions=tuple(
                PalContribution(amount=_money(c["amount"], "DKK"))
                for c in r.get("contributions", [])
            ),
            withdrawals=tuple(
                PalWithdrawal(amount=_money(w["amount"], "DKK")) for w in r.get("withdrawals", [])
            ),
        )

    return cast(PalInput, _safe_decode("pal input", raw, _do))


def _decode_vorab(raw: Mapping[str, Any]) -> VorabInput:
    def _do(r: Mapping[str, Any]) -> VorabInput:
        return VorabInput(
            isin=str(r["isin"]),
            tax_year=int(r["tax_year"]),
            classification=r["classification"],
            start_value=_money(r["start_value"], "EUR"),
            end_value=_money(r["end_value"], "EUR"),
            distributions=_money(r.get("distributions", "0"), "EUR"),
            holding_months=int(r.get("holding_months", 12)),
        )

    return cast(VorabInput, _safe_decode("vorab input", raw, _do))


def _convert(
    amount: Decimal,
    *,
    native: Currency,
    target: Currency,
    fx: Mapping[str, Decimal],
) -> Decimal:
    if native == target or amount == 0:
        return amount
    key = f"{native}_to_{target}"
    if key not in fx:
        raise CliError(
            f"missing FX rate {key!r}; supply it via input.fx to convert "
            f"{native} amounts to {target}"
        )
    return amount * fx[key]


def _parse_fx(raw: Mapping[str, Any] | None) -> dict[str, Decimal]:
    if not raw:
        return {}
    out: dict[str, Decimal] = {}
    for k, v in raw.items():
        if not isinstance(k, str):
            raise CliError(f"fx keys must be strings, got {type(k).__name__}")
        out[k] = Decimal(str(v))
    return out


def _round(amount: Decimal) -> float:
    """Quantize to 2dp and return as a JSON-friendly float."""
    return float(_q(amount))


def _dk_report(
    *,
    year: int,
    target_currency: Currency,
    fx: Mapping[str, Decimal],
    spec: Mapping[str, Any],
) -> dict[str, Any]:
    lager_in = [_decode_lager(r) for r in spec.get("lager", [])]
    pal_in = [_decode_pal(r) for r in spec.get("pal", [])]
    ask_specs = spec.get("ask", []) or []

    lager_results: list[LagerResult] = [compute_lager(li) for li in lager_in if li.tax_year == year]
    pal_results: list[PalResult] = [compute_pal(pi) for pi in pal_in if pi.tax_year == year]

    ask_results: list[AskTaxResult] = []
    for ask_raw in ask_specs:
        account_id = str(ask_raw["account_id"])
        ask_lager_inputs = [_decode_lager(r) for r in ask_raw.get("lager", [])]
        ask_lager_in_year = [li for li in ask_lager_inputs if li.tax_year == year]
        if not ask_lager_in_year:
            continue
        ask_lager_results = [compute_lager(li) for li in ask_lager_in_year]
        ask_results.append(
            compute_ask_taxes(
                account_id=account_id,
                tax_year=year,
                lager_results=ask_lager_results,
            )
        )

    prior_loss = _money(spec.get("prior_loss_carry_forward", "0"), "DKK")
    report = build_skat_report(
        tax_year=year,
        lager_results=lager_results,
        ask_results=ask_results,
        pal_results=pal_results,
        prior_loss_carry_forward=prior_loss,
    )

    def conv(d: Decimal) -> float:
        return _round(_convert(d, native="DKK", target=target_currency, fx=fx))

    line_items: list[dict[str, Any]] = []
    for row in report.rows:
        line_items.append(
            {
                "category": row.category,
                "amount": conv(row.gain.amount),
                "source": row.source_id,
            }
        )
        if row.tax_withheld.amount != 0:
            line_items.append(
                {
                    "category": f"{row.category}_tax_withheld",
                    "amount": conv(row.tax_withheld.amount),
                    "source": row.source_id,
                }
            )

    summary = {
        "gross_capital_income": conv(report.gross_capital_income.amount),
        "taxable_capital_income": conv(report.taxable_capital_income.amount),
        "loss_carry_forward": conv(report.loss_carry_forward.amount),
        "tax_withheld_total": conv(report.tax_withheld_total.amount),
        "prior_loss_carry_forward": conv(report.prior_loss_carry_forward.amount),
    }

    return {
        "year": year,
        "jurisdiction": "DK",
        "currency": target_currency,
        "summary": summary,
        "line_items": line_items,
    }


def _de_report(
    *,
    year: int,
    target_currency: Currency,
    fx: Mapping[str, Decimal],
    spec: Mapping[str, Any],
) -> dict[str, Any]:
    vorab_in = [_decode_vorab(r) for r in spec.get("vorab", [])]
    results: list[VorabResult] = [
        compute_vorabpauschale(vi) for vi in vorab_in if vi.tax_year == year
    ]

    def conv(d: Decimal) -> float:
        return _round(_convert(d, native="EUR", target=target_currency, fx=fx))

    total_vorab = sum((r.vorabpauschale.amount for r in results), Decimal(0))
    total_taxable = sum((r.taxable.amount for r in results), Decimal(0))
    total_tax_due = sum((r.tax_due.amount for r in results), Decimal(0))

    line_items: list[dict[str, Any]] = []
    for r in results:
        source = f"de_vorab:{r.isin}"
        line_items.append(
            {
                "category": "vorabpauschale",
                "amount": conv(r.vorabpauschale.amount),
                "source": source,
            }
        )
        line_items.append(
            {
                "category": "vorab_taxable",
                "amount": conv(r.taxable.amount),
                "source": source,
            }
        )
        line_items.append(
            {
                "category": "vorab_tax_due",
                "amount": conv(r.tax_due.amount),
                "source": source,
            }
        )

    summary = {
        "total_vorabpauschale": conv(total_vorab),
        "total_taxable": conv(total_taxable),
        "total_tax_due": conv(total_tax_due),
    }

    return {
        "year": year,
        "jurisdiction": "DE",
        "currency": target_currency,
        "summary": summary,
        "line_items": line_items,
    }


def _resolve_input(year: int, input_arg: str | None) -> Mapping[str, Any]:
    """Load the JSON spec from --input, stdin, or the default path."""
    if input_arg == "-":
        text = sys.stdin.read()
        return _loads(text)
    if input_arg:
        path = Path(input_arg)
        if not path.exists():
            raise CliError(f"input file not found: {path}")
        return _loads(path.read_text(encoding="utf-8"))

    base = os.environ.get("PENGE_TAX_INPUTS_DIR", "data/tax")
    default_path = Path(base) / f"{year}.json"
    if default_path.exists():
        return _loads(default_path.read_text(encoding="utf-8"))
    return {}


def _loads(text: str) -> Mapping[str, Any]:
    if not text.strip():
        return {}
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise CliError(f"input is not valid JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise CliError("input JSON must be an object at the top level")
    return data


def _parse_jurisdictions(value: str) -> list[Jurisdiction]:
    parts = [p.strip().upper() for p in value.split(",") if p.strip()]
    out: list[Jurisdiction] = []
    for p in parts:
        if p not in ("DK", "DE"):
            raise CliError(f"unknown jurisdiction {p!r}; expected DK or DE")
        jur = cast(Jurisdiction, p)
        if jur in out:
            raise CliError(f"duplicate jurisdiction {p!r}")
        out.append(jur)
    if not out:
        raise CliError("at least one jurisdiction is required")
    return out


def compute_tax_year(
    *,
    year: int,
    currency: Currency,
    jurisdictions: Iterable[Jurisdiction],
    spec: Mapping[str, Any],
) -> list[dict[str, Any]]:
    """Pure entry point: build the per-jurisdiction tax report."""
    fx = _parse_fx(spec.get("fx"))
    out: list[dict[str, Any]] = []
    for jur in jurisdictions:
        if jur == "DK":
            out.append(
                _dk_report(
                    year=year,
                    target_currency=currency,
                    fx=fx,
                    spec=spec.get("dk", {}) or {},
                )
            )
        elif jur == "DE":
            out.append(
                _de_report(
                    year=year,
                    target_currency=currency,
                    fx=fx,
                    spec=spec.get("de", {}) or {},
                )
            )
        else:  # pragma: no cover - guarded by parser
            raise CliError(f"unknown jurisdiction {jur!r}")
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="penge-tax-year",
        description="Compute a per-jurisdiction tax report for one tax year.",
    )
    parser.add_argument("--year", type=int, required=True)
    parser.add_argument("--currency", choices=("EUR", "DKK"), required=True)
    parser.add_argument(
        "--jurisdictions",
        required=True,
        help="Comma-separated list, e.g. 'DK' or 'DK,DE'.",
    )
    parser.add_argument(
        "--input",
        help=(
            "Path to a JSON spec, '-' for stdin, or omit to load "
            "${PENGE_TAX_INPUTS_DIR:-data/tax}/<year>.json (treated as "
            "empty if not present)."
        ),
    )
    args = parser.parse_args(argv)

    try:
        jurs = _parse_jurisdictions(args.jurisdictions)
        spec = _resolve_input(args.year, args.input)
        result = compute_tax_year(
            year=args.year,
            currency=args.currency,
            jurisdictions=jurs,
            spec=spec,
        )
    except CliError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    except ValidationError as exc:
        # Format errors as <loc>: <msg> only — never echo the offending
        # input value, which on this codebase can be a real holding
        # amount or account identifier and would leak via the MCP
        # subprocess stderr capture into audit logs.
        details = "; ".join(
            f"{'.'.join(str(p) for p in err['loc']) or '<root>'}: {err['msg']}"
            for err in exc.errors()
        )
        print(f"error: invalid input: {details}", file=sys.stderr)
        return 2
    except Exception as exc:  # pragma: no cover - last-resort guard
        print(f"error: {exc}", file=sys.stderr)
        return 1

    json.dump(result, sys.stdout, separators=(",", ":"), sort_keys=False)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
