"""PAL-skat (pensionsafkastskat) — 15.3 % yield tax on Danish pension pots.

Danish pension providers (PFA, Velliv, AP Pension, ...) are required
to pay an annual *pensionsafkastskat* (PAL-skat) of **15.3 %** on the
return generated by pension assets. The provider withholds and remits
this tax automatically; the saver sees only a net-of-tax account
balance. This module gives Penge a deterministic shadow calculation
so simulations and tax projections can stay net-of-tax even when raw
gross returns are observed elsewhere.

Formula (per pension account, per tax year):

    return = end_market_value
           - start_market_value
           - Σ contributions
           + Σ withdrawals
    tax    = max(return, 0) * 0.153

A negative return produces zero tax due and a ``loss_carry_forward``
amount. PAL-skat allows losses to be carried forward indefinitely
against future positive returns; the cross-year roll-forward
bookkeeping is the SKAT report generator's responsibility (#39).

References:

* SKAT — `Pensionsafkastskat
  <https://skat.dk/borger/pension/pensionsafkastskat>`_
* :doc:`/tax/dk` — PAL-skat section
* ADR-0019 — PAL-skat tracking on PFA
"""

from __future__ import annotations

from collections.abc import Iterable
from decimal import ROUND_HALF_EVEN, Decimal
from typing import Final, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

from penge.tax.lots import Money

__all__ = [
    "PAL_RATE",
    "PalContribution",
    "PalError",
    "PalInput",
    "PalResult",
    "PalWithdrawal",
    "compute_pal",
]

_MONEY_DP = Decimal("0.01")
_DKK: Final[Literal["DKK"]] = "DKK"

PAL_RATE: Final = Decimal("0.153")
"""Statutory PAL-skat rate (15.3 %)."""


def _q(value: Decimal) -> Decimal:
    return value.quantize(_MONEY_DP, rounding=ROUND_HALF_EVEN)


class PalError(Exception):
    """Raised when a PAL input is inconsistent (e.g. wrong currency)."""


def _ensure_dkk_nonneg(v: Money, *, label: str) -> Money:
    if v.currency != _DKK:
        raise PalError(f"{label} must be DKK, got {v.currency}")
    if v.amount < 0:
        raise PalError(f"{label} must be non-negative")
    return v


class PalContribution(BaseModel):
    """A contribution into the pension account during the tax year, in DKK."""

    model_config = ConfigDict(frozen=True)

    amount: Money

    @field_validator("amount")
    @classmethod
    def _dkk(cls, v: Money) -> Money:
        return _ensure_dkk_nonneg(v, label="PalContribution.amount")


class PalWithdrawal(BaseModel):
    """A withdrawal from the pension account during the tax year, in DKK."""

    model_config = ConfigDict(frozen=True)

    amount: Money

    @field_validator("amount")
    @classmethod
    def _dkk(cls, v: Money) -> Money:
        return _ensure_dkk_nonneg(v, label="PalWithdrawal.amount")


class PalInput(BaseModel):
    """All data required to compute PAL-skat for one account, one year."""

    model_config = ConfigDict(frozen=True)

    account_id: str = Field(..., min_length=1)
    tax_year: int = Field(..., ge=1900, le=2999)
    start_market_value: Money
    end_market_value: Money
    contributions: tuple[PalContribution, ...] = ()
    withdrawals: tuple[PalWithdrawal, ...] = ()

    @field_validator("start_market_value", "end_market_value")
    @classmethod
    def _mv_dkk(cls, v: Money) -> Money:
        return _ensure_dkk_nonneg(v, label="market value")


class PalResult(BaseModel):
    """Per-account, per-year PAL-skat result in DKK."""

    model_config = ConfigDict(frozen=True)

    account_id: str
    tax_year: int
    start_market_value: Money
    end_market_value: Money
    contributions_total: Money
    withdrawals_total: Money
    return_amount: Money
    """Computed pension return (positive = gain, negative = loss)."""

    tax_due: Money
    """15.3 % of ``return_amount`` if positive, otherwise 0 DKK."""

    loss_carry_forward: Money
    """Magnitude of the negative return available for future-year offset (DKK)."""


def compute_pal(inp: PalInput) -> PalResult:
    """Compute PAL-skat for one pension account in one tax year.

    Pure function — no I/O, no FX. Caller must convert all monetary
    inputs to DKK first (typically already DKK because PFA reports
    in DKK).
    """

    contrib_sum = sum((c.amount.amount for c in inp.contributions), Decimal("0"))
    wd_sum = sum((w.amount.amount for w in inp.withdrawals), Decimal("0"))

    return_amount = (
        inp.end_market_value.amount - inp.start_market_value.amount - contrib_sum + wd_sum
    )

    if return_amount > 0:
        tax = return_amount * PAL_RATE
        loss = Decimal("0")
    else:
        tax = Decimal("0")
        loss = -return_amount

    return PalResult(
        account_id=inp.account_id,
        tax_year=inp.tax_year,
        start_market_value=Money(amount=_q(inp.start_market_value.amount), currency=_DKK),
        end_market_value=Money(amount=_q(inp.end_market_value.amount), currency=_DKK),
        contributions_total=Money(amount=_q(contrib_sum), currency=_DKK),
        withdrawals_total=Money(amount=_q(wd_sum), currency=_DKK),
        return_amount=Money(amount=_q(return_amount), currency=_DKK),
        tax_due=Money(amount=_q(tax), currency=_DKK),
        loss_carry_forward=Money(amount=_q(loss), currency=_DKK),
    )


def compute_pal_many(inputs: Iterable[PalInput]) -> list[PalResult]:
    """Convenience: compute PAL for many account-year pairs, preserving order."""

    return [compute_pal(i) for i in inputs]
